new

diff --git a/.github/workflows/ci-build-test.yml b/.github/workflows/ci-build-test.yml
--- a/.github/workflows/ci-build-test.yml
+++ b/.github/workflows/ci-build-test.yml
@@ -33,9 +33,25 @@ jobs:
         run: docker run -d -p 5000:5000 --name prod-container cicd-prod
 
       # Step 4: Wait for application to start
-      - name: Wait for app
-        run: sleep 5
+      - name: Wait for app (fail if not ready)
+        run: 
+          for i in {1..10};do
+            if curl -s http://localhost:5000;then
+              echo "App is up!"
+              exit 0
+              fi
+              echo "waiting for app"
+              sleep 2
+            done
+
+            echo "App failed to start"
+            exit 1 
 
       # Step 5: Run tests
       - name: Check if app is running
         run: curl -f http://localhost:5000
+
+      # clean container
+      - name : Cleanup Container
+        if : always()
+        run : docker stop prod-container && docker rm prod-container
